# Generated by Django 4.1.7 on 2023-02-15 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_alter_shops_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adress',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='shops',
            old_name='adress_id',
            new_name='address_id',
        ),
    ]
