# Generated by Django 4.1.6 on 2023-02-18 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0004_alter_address_id_alter_city_id_alter_street_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shops',
            name='address_id',
        ),
        migrations.AddField(
            model_name='shops',
            name='house',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='shops',
            name='street_id',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.RESTRICT, to='tutorials.street'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
