# Generated by Django 4.1.6 on 2023-02-22 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0005_remove_shops_address_id_shops_house_shops_street_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='street',
            old_name='city_id',
            new_name='city',
        ),
        migrations.RemoveField(
            model_name='shops',
            name='street_id',
        ),
        migrations.AddField(
            model_name='shops',
            name='street',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, to='tutorials.street'),
        ),
        migrations.AlterField(
            model_name='shops',
            name='house',
            field=models.CharField(default='', max_length=10),
        ),
    ]
