# Generated by Django 4.1.6 on 2023-03-03 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0007_alter_shops_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shops',
            name='close_time',
        ),
        migrations.RemoveField(
            model_name='shops',
            name='open_time',
        ),
    ]
