# Generated by Django 4.1.6 on 2023-03-03 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0008_remove_shops_close_time_remove_shops_open_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='shops',
            name='close_time',
            field=models.TimeField(default='00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shops',
            name='open_time',
            field=models.TimeField(default='00:00:00'),
            preserve_default=False,
        ),
    ]
