# Generated by Django 4.1.6 on 2023-03-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0009_shops_close_time_shops_open_time'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='shops',
            constraint=models.UniqueConstraint(fields=('house', 'street', 'name'), name='ShopsUniqueConstraint'),
        ),
        migrations.AddConstraint(
            model_name='street',
            constraint=models.UniqueConstraint(fields=('name', 'city'), name='StreetUniqueConstraint'),
        ),
    ]
