version: '3.7'

services:
  rest_api:
    networks:
      shop-local-network:
        aliases:
          - rest_api
    container_name: rest_api
    build:
      context: ../
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    networks:
      - shop-local-network
    container_name: postgres_db
    ports:
      - 15432:5432
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/shop/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
volumes:
  postgres_data:

networks:
  shop-local-network:
    driver: bridge